version: '2'

services:

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs:/logs
      - ./dist:/usr/share/nginx/html:ro
